version: 2.0

jobs:
  "test": &test
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/arunsworld/nursery
    steps: &steps
      - checkout
      - run: go test -v -race -cover ./...

workflows:
  version: 2
  build:
    jobs:
      - "test"